### ISSUE TITLE
[KAHF]Transfer amount should not include fee

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#110]
![image](https://user-images.githubusercontent.com/22833166/128722724-da3a782d-7692-4f63-9f58-e92ee2e64f79.png)

**Comment by forchain** [comment]
Only in iOS, android is fine

**Comment by gzh1612** [comment]
Is it because IOS is not the latest

**Comment by forchain** [comment]
verify iOS later
