### ISSUE TITLE
[KAHF]Crashes on opening 'Transaction reminder me'

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#114]
![image](https://user-images.githubusercontent.com/22833166/128733525-270e6fb4-cd60-421a-b6b6-c22b68eec263.png)

**Comment by gzh1612** [comment]
I think this function can be removed

**Comment by gzh1612** [comment]
I think this function can be removed

**Comment by forchain** [comment]
not removed yet

**Comment by forchain** [comment]
fixed
