### ISSUE TITLE
[KAHF]Cannot add Meer address book

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#115]
![image](https://user-images.githubusercontent.com/22833166/128733757-09360b63-4c7a-4c0c-bf51-851cea426c89.png)

**Comment by gzh1612** [comment]
![image](https://user-images.githubusercontent.com/48427480/129160990-57b9e245-ddf1-4a65-98d2-1ec12bd6499b.png)
This is displayed in the new version

**Comment by forchain** [comment]
verified
