### ISSUE TITLE
[KAHF]No detail page for version updates

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#116]
Cannot review the details of each update, please add linking page or at least add update time.
![image](https://user-images.githubusercontent.com/22833166/128734726-2c2d2528-0f8b-45dd-a929-e214478d98d4.png)

**Comment by gzh1612** [comment]
![image](https://user-images.githubusercontent.com/48427480/129158509-31f0772d-0efe-43fc-8110-ae8d7ef8b4d0.png)

This is displayed in the new version

**Comment by forchain** [comment]
verified
