### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-wallet#12]
![001wallet](https://user-images.githubusercontent.com/32875657/71360049-77654080-25c9-11ea-90e8-2dc87f3f5980.png)
![002wallet](https://user-images.githubusercontent.com/32875657/71360058-7d5b2180-25c9-11ea-97a9-8d8fd41587af.png)
![003wallet](https://user-images.githubusercontent.com/32875657/71360067-84822f80-25c9-11ea-8097-86704b19a005.png)
![004wallet](https://user-images.githubusercontent.com/32875657/71360071-89df7a00-25c9-11ea-841b-881065ccfded.png)
![005wallet](https://user-images.githubusercontent.com/32875657/71360076-8e0b9780-25c9-11ea-925f-1ee18a7a8ef9.png)
![006wallet](https://user-images.githubusercontent.com/32875657/71360078-919f1e80-25c9-11ea-8d0b-bdc4c571e73b.png)
![007wallet](https://user-images.githubusercontent.com/32875657/71360084-95cb3c00-25c9-11ea-8f1c-ae81c8e3ee42.png)
![008wallet](https://user-images.githubusercontent.com/32875657/71360119-b0051a00-25c9-11ea-8cd6-0602489ab206.png)
![009wallet](https://user-images.githubusercontent.com/32875657/71360122-b4313780-25c9-11ea-90f2-f4e56e3b8080.png)
![010wallet](https://user-images.githubusercontent.com/32875657/71360126-b8f5eb80-25c9-11ea-9ff8-acfd83230b3f.png)

这个编译过程是否正确，从头到尾连续截图

**Comment by dindinw** [comment]
@blocklee  Please try the latest code. the Makefile has never been tried in the windows (MINGW) environment.  Looks the go build is ok. You can ignore the js error if you are not using the web mode. 
BTW, better to provide txt error msg output, I could hardly recognize words in your screen shoots.
