### ISSUE TITLE
钱包转账失败

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer-wallet#13]
按教程
https://www.qitmeertalk.org/t/qitmeer-wallet-pc/927
尝试转账

$ ./qitmeer-wallet qc listaccountsbalance
default:0
imported:37800
$ ./qitmeer-wallet qc sendtoaddress TmhEDGfGAEuV5rWkVgCXXXXXXXXXXXX 8 123456
sendToAddress: error -32603: balance is not enough

**Comment by rlinxy** [comment]
是哪里做错了么？还是怎么才能用imported账户支付转账金额？谢谢

**Comment by dindinw** [comment]
@rlinxy please try the latest code.
