### ISSUE TITLE
Is there a compiled version?

### ISSUE THREAD

**Issue by 1617176084** [Qitmeer/qitmeer-wallet#134]
Is there a discord site? I want to join the community

**Comment by dindinw** [comment]
There is only complied version for [`qitmeer` node](https://github.com/Qitmeer/qitmeer/releases). and [kahf wallet](https://www.kahf.io/) (iOS/Android)  for the end user. The `qitmeer-wallet` is supposed for developer & advanced user who can build easily from source and contribute to the repo. PRs are generally welcomed! 
There is not discord channel currently. We may consider to build one dev channel if more interests accumulated anyway the project has been lasted little known for years.  
Thanks for your concern.
