### ISSUE TITLE
create a entropy in qitmeer-wallet,and convert it into mnemonic. then import mnemonic into kafh wallet,but i got different  private key and address between kafh and  qitmeer-wallet.

### ISSUE THREAD

**Issue by areyacloud** [Qitmeer/qitmeer-wallet#135]
create a entropy in qitmeer-wallet,and convert it into mnemonic. then import mnemonic into kafh wallet,but i got different private key and address between kafh and  qitmeer-wallet. i think this is a issue

**Comment by dindinw** [comment]
Thank for your information, Could you provide more details for reproducing the issue.

**Comment by areyacloud** [comment]
- i create a wallet with qitmeer-wallet cli,got entropy seed and private key: 
`Your wallet generation seed is:
3691ee4943b6e8721e13636648b974244d37e7446d2b4918f665a15881ae7a10
IMPORTANT: Keep the seed in a safe place as you
will NOT be able to restore your wallet without it.
Please keep in mind that anyone who has access
to the seed can also restore your wallet thereby
giving them access to all your funds, so it is
imperative that you keep it in a secure location.
Once you have stored the seed in a safe and secure location, enter "OK" to continue: OK
Creating the wallet...
pri:6595f5e9e009efb6fc17a510ca5318f1bf8a8800d02e7bab4654dbb3d51b1f8a
The wallet has been created successfully.
createWallet succ`
- i wish to use kafh app,so i convert the entropy to mnemonic with qx cli
`root@iZ8vbbzq0e6b75f4tkxpu3Z:~/qitmeer/cmd/qx# ./qx mnemonic-new 3691ee4943b6e8721e13636648b974244d37e7446d2b4918f665a15881ae7a10
custom month myself manual hub decorate joke hockey green easy fringe embrace square victory balance pistol empower sibling offer dress marine strong tribe among`
- and i import mnemonic words into kafh wallet 
![image](https://user-images.githubusercontent.com/35396544/149338322-6b21ba3a-a150-4a02-bf29-776f5065e07d.png)
- here i found the issue ,the private is not exactly the one i created in step 1,so is the address
![image](https://user-images.githubusercontent.com/35396544/149338466-0f959e69-5a9d-4fa1-ae05-47199eb8e03a.png)

**Comment by dindinw** [comment]
@areyacloud thanks for your help, we will look into it.

**Comment by areyacloud** [comment]
> [<img alt="@dindinw" width="20" height="20" src="https://avatars.githubusercontent.com/u/1134993?s=60&amp;u=c2611c49a0d4cb46d53a1740bec9ae69c0eb7714&amp;v=4">](/dindinw) [dindinw](/dindinw) assigned [jamesvan2019](/jamesvan2019) [7小时前](#event-5887420024)

i noticed that kafh wallet generate 12 mnemonic words,so its entropy should be 128 bit; while qitmeer-wallet and qx cli generate  24 mnemonic words, so its entropy length is 256 bit。im confused , which one is correct? kafh?

**Comment by areyacloud** [comment]
@areyacloud  here's another issue,wallet cannot sync on some height in web mode ,can i add develope's wechat?

**Comment by areyacloud** [comment]
9f3402c  
742444b
check on these two commits plz, same seed，they generate different privkey and address

**Comment by dindinw** [comment]
@areyacloud 
you can try https://github.com/jamesvan2019/qitmeer-wallet/tree/wallet if you can't wait for the PR review process.  thanks
