### ISSUE TITLE
stuck while syncing blocks

### ISSUE THREAD

**Issue by areyacloud** [Qitmeer/qitmeer-wallet#136]
`root@iZ8vbbzq0e6b75f4tkxpu3Z:~/qitmeer-wallet/build/bin/block-wallet# ./qitmeer-wallet web
web model
2022-01-14|10:30:05.411 [INFO ] Established connection to RPC server 172.17.162.67:8133 module=RPCCLI
2022-01-14|10:30:05.412 [INFO ] notification rescan block           start=0 end=319556
update history blcok:199999/319556`

stuck on this height, i tried to reboot,but useless

**Comment by areyacloud** [comment]
![image](https://user-images.githubusercontent.com/35396544/149508891-bcd6936b-89d7-4d9f-a1e7-916d738a91fe.png)

still stuck here

**Comment by jamesvan2019** [comment]
This [PR](https://github.com/Qitmeer/qitmeer/pull/694) can solve the problem

**Comment by dindinw** [comment]
@areyacloud the bug should have been resolved by the latest version of [the qitmeer master branch](https://github.com/Qitmeer/qitmeer/tree/master)
