### ISSUE TITLE
是否有批量转账功能？

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer-wallet#20]
如果没有批量转账，例如bitcoin的sendmany，那么能否开发个批量支付接口。

矿池之类大规模支付场景下，调用sendtoaddress一个一个支付不太合适。会有各种问题，例如一个50000的utxo，支付300个后就要冻结整个utxo直到找零确认后，才能用剩下的49700。

手机kahf钱包有批量支付，那现成代码可否移植到qitmeer-wallet呢？

谢谢

**Comment by bbkbk222** [comment]
为什么没人回复

**Comment by dindinw** [comment]
@rlinxy if you want RPC like https://bitcoincore.org/en/doc/0.16.0/rpc/wallet/sendmany/,  please help us to create to benefit the community. Your PR is welcome. `kahf-wallet` remains a different implementation based on a different source, which is commercial software, what their maintainer's decision is independent with the `qitmeer-wallet` project.
@bbkbk222 When we call software “free,” we mean that it respects the users' essential freedoms: the freedom to run it, to study and change it, and to redistribute copies with or without changes. This is a matter of freedom, not price, so think of “free speech,” not “free beer.”
https://www.gnu.org/philosophy/open-source-misses-the-point.en.html
