### ISSUE TITLE
required maturity of 720 blocks

### ISSUE THREAD

**Issue by t01001** [Qitmeer/qitmeer-wallet#29]
cmd:
qitmeer-wallet -c  config.toml --confirmations 720  qc sendtoaddress $ADDR $AMOUNT $PASS

error:
sendToAddress: error -32603: sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Rule Error : Rejected transaction 17826602877e500b92d95ebde3013d2ad89d6dc9c2802a0f10d1320ac9bb419c: tx 17826602877e500b92d95ebde3013d2ad89d6dc9c2802a0f10d1320ac9bb419c tried to spend coinbase transaction f33e25e80c6a740cd6c6c23cc01728c68847fa6f4290035c0bcf9c7854b29300 from at 384 before required maturity of 720 blocks"}}

**Comment by dindinw** [comment]
@t01001 the `coinbase` UTXO needs to wait for 720 blocks before you can spend it. Please send the transaction again to test if it works for you.

**Comment by forchain** [comment]
By Design, the maturity of **COINBASE** transaction is for safety consideration
