### ISSUE TITLE
the txlist display error

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-wallet#34]
the txlist display for qitmeer-wallet are not match with qitmeer explorer tx display for the same adddress.

- tx display on qitmeer explorer

![image](https://user-images.githubusercontent.com/32875657/86312851-3aec5e80-bc56-11ea-9656-5ae8a1ddf759.png)

Only six trading messages.

- tx display on qitmeer-wallet txlist

![image](https://user-images.githubusercontent.com/32875657/86312506-70447c80-bc55-11ea-9321-8eb56ab23f7a.png)
![image](https://user-images.githubusercontent.com/32875657/86312561-9702b300-bc55-11ea-97bc-f33e3390be52.png)

There are 11 TX displays.

**Comment by dindinw** [comment]
The display of `qitmeer-wallet` screen-shot shows some duplicated tx-id, 
The Tx list of qitmeer explorer can be find from  https://explorer.qitmeer.io/address/TmUWxxq66VCdAJtf5kxPVGwHN8LzXyqRk8L
it might be a bug here. will look into this.

**Comment by forchain** [comment]
Problem identified
1. getlisttxbyaddr lists transactions based on outputs number
2. count CHANGEs as inward transactions
3. outward transactions not implemented

**Comment by forchain** [comment]
https://github.com/Qitmeer/qitmeer-wallet/blob/1d626a2b698dbd56dcb1479b12d616fb91ac82bd/wallet/wallet.go#L590

**Comment by blocklee** [comment]
The in and out parameters in the getlisttxbyaddr command don't seem to work.

**Comment by forchain** [comment]
> The in and out parameters in the getlisttxbyaddr command don't seem to work.

Yes, there are bugs, fixing

**Comment by blocklee** [comment]
I find that the results of getlisttxbyaddr are not normal for some address with fewer transactions.  But I can get normal results from the explorer.

- addr1: Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2

```json
\qitmeer-wallet>qitmeer-wallet.exe qc getlisttxbyaddr Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2
Using config file: config.toml
{
 "total": 0,
 "page": 1,
 "page_size": 1000000000
}
```

that on explorer for this addr: https://meerscan.io/address/Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2

- addr2: TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE

```json
\qitmeer-wallet>qitmeer-wallet.exe qc getlisttxbyaddr TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE
Using config file: config.toml
{
 "total": 0,
 "page": 1,
 "page_size": 1000000000
}
```

that on explorer for this addr: https://meerscan.io/address/TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE

**Comment by blocklee** [comment]
Another suggestion:

**Is the getlisttxbyaddr command intended to get just the txid, or all the transaction details?**

Now this command gives gives the full details of the transaction, but I probably don't need to pay attention to that much. I just want to get **the list of txid**, because I can get the details of each transaction by the command `gettx`.

**Comment by blocklee** [comment]
> I find that the results of getlisttxbyaddr are not normal for some address with fewer transactions. But I can get normal results from the explorer.
> 
> * addr1: Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2
> 
> ```json
> \qitmeer-wallet>qitmeer-wallet.exe qc getlisttxbyaddr Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2
> Using config file: config.toml
> {
>  "total": 0,
>  "page": 1,
>  "page_size": 1000000000
> }
> ```
> 
> that on explorer for this addr: https://meerscan.io/address/Tmc3tTH3TT2fA3LzwiL2s4hWGd89fHLTCp2
> 
> * addr2: TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE
> 
> ```json
> \qitmeer-wallet>qitmeer-wallet.exe qc getlisttxbyaddr TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE
> Using config file: config.toml
> {
>  "total": 0,
>  "page": 1,
>  "page_size": 1000000000
> }
> ```
> 
> that on explorer for this addr: https://meerscan.io/address/TmbXAkqUPnmqvNYFwjVVQcqoVPpewfQqkdE

I think I find the problem, its my fault, I have not updateblock to the latest, I'm sorry.
