### ISSUE TITLE
私钥导入问题

### ISSUE THREAD

**Issue by huzhiyang888** [Qitmeer/qitmeer-wallet#44]
我们调用wallet_importPrivKey这个方法的时候  提示 私钥导入这个rpc 已经弃用？ 请问还有什么办法 可以进行私钥导入钱包 账户 然后进行转账

**Comment by forchain** [comment]
https://github.com/Qitmeer/docs/issues/49
文档没有更新，已经提交文档bug

**Comment by forchain** [comment]
https://github.com/Qitmeer/qitmeer-wallet/issues/36
这个功能造成的影响

**Comment by huzhiyang888** [comment]
这个功能导致我没有办法把交易所用户地址里的币 转出来！

**Comment by forchain** [comment]
![image](https://user-images.githubusercontent.com/22833166/86771312-95395500-c084-11ea-954f-ae100d8f926c.png)

**Comment by forchain** [comment]
不是#36 导致的，#36只是改了命令行，而且也只是加了一个可选参数，但这个问题是RPC，正在排查具体原因

**Comment by huzhiyang888** [comment]
冒昧问下 #36  啥意思

**Comment by forchain** [comment]
> 冒昧问下 #36 啥意思

客气了，命令行工具之前支持hash256的私钥格式，不支持WIF格式（但是钱包RPC支持），这个功能就是支持这个格式

**Comment by forchain** [comment]
@huzhiyang888 
问题已经查明，是 https://github.com/Qitmeer/qitmeer-wallet/commit/283cfcd3989001245f17c9596eaf22684de2f2bd#diff-50d8a68d7015a559e6782731522920e9R202 这个改动造成的，暂不清楚为什么这么改的原因

**Comment by huzhiyang888** [comment]
查出来就行！修复好更新下

**Comment by forchain** [comment]
> @huzhiyang888
> 问题已经查明，是 [283cfcd#diff-50d8a68d7015a559e6782731522920e9R202](https://github.com/Qitmeer/qitmeer-wallet/commit/283cfcd3989001245f17c9596eaf22684de2f2bd#diff-50d8a68d7015a559e6782731522920e9R202) 这个改动造成的，暂不清楚为什么这么改的原因

上面那个是其他问题，这两个问题才是导致这个bug的

https://github.com/Qitmeer/qitmeer-wallet/commit/4f5dc31ce77730f30f0bebedd4cbe24e1aa1c6c7#diff-507294bc07e5af801e24a9ae2e7f2eafR221

https://github.com/Qitmeer/qitmeer-wallet/commit/4f5dc31ce77730f30f0bebedd4cbe24e1aa1c6c7#diff-507294bc07e5af801e24a9ae2e7f2eafR255

**Comment by forchain** [comment]
#46
@huzhiyang888 已修复，等待review
