### ISSUE TITLE
version management

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#45]
qitmeer-wallet updates would break dependent exchanges

**Comment by dindinw** [comment]
The `qitmeer-wallet` itself should also be improved for version support. currently no command `version` or `--version` here. 
```
$ ./qitmeer-wallet version
Error: unknown command "version" for "qitmeer-wallet"
$ ./qitmeer-wallet --version
Error: unknown flag: --version
```

**Comment by forchain** [comment]
> The `qitmeer-wallet` itself should also be improved for version support. currently no command `version` or `--version` here.
> 
> ```
> $ ./qitmeer-wallet version
> Error: unknown command "version" for "qitmeer-wallet"
> $ ./qitmeer-wallet --version
> Error: unknown flag: --version
> ```

Good point, will be included

**Comment by forchain** [comment]
create a GitHub workflow to generate builds
