### ISSUE TITLE
qitmeer-wallet qx command “wiftopri”  checksum error

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-wallet#50]
I want to get the private key from wif key, then get the address from privkey.

When using `qx wiftopri` command, checksum error occured.
 
I export wif format private key by address first using the dumpPrivKey command of console.

```bash
wallet-cli:dumpPrivKey TmQyhXMk6KsCU7PVh5S6ayE8B2DthJ1HUoj
9Qva4XJ319QifFd83HC99sZWyhx8gUG2h42P7WXjuP2MsSjwRkoLd
```

Then using qx wiftopri to get privkey, error occured.

```bash
D:\git\qitmeer-wallet>qitmeer-wallet.exe qx wiftopri 9Qva4XJ319QifFd83HC99sZWyhx8gUG2h42P7WXjuP2MsSjwRkoLd
Using config file: config.toml
Qx Error : "checksum error"
```

**Comment by forchain** [comment]
dumpPrivKey  is using
https://github.com/Qitmeer/qitmeer-wallet/blob/1673f4a4e666147f120da5a625b75a737c92cc0e/utils/wif.go#L85

while wiftopri is using
https://github.com/Qitmeer/qitmeer/blob/71a040b03be58c7f828e825440dfbf432ee75456/qx/handle_crypto.go#L252

**Comment by forchain** [comment]
Thanks clarification from @dindinw, my understanding of the difference from the two as follow:

Qitmeer WIF should be compatible  with  BTC main net.So the Network ID must be  0x80.

The DecodeWIF in qitmeer-wallet is just for **base58check** debugging, we could detect it by qitmeer qx 
```shell
$ qx base58check-decode -d 9Qva4XJ319QifFd83HC99sZWyhx8gUG2h42P7WXjuP2MsSjwRkoLd
mode    : qitmeer
version : 0ce2 (hex) 3298 (BE) 57868 (LE)
payload : 617e729455b42dd6c12fcb0f16613d7251672e8cc12390a65d334dd36ca0335801
checksum: 76c269e2 (hex) 1992452578 (BE) 3798581878 (LE)
```

The corresponding BTC WIF is KzVE5hmNC6UpHF8zAzvEDqd2nbGp9iUH1bfwiZTnt9HcsRLqrgso
```shell
$ qx base58check-decode -m btc -d KzVE5hmNC6UpHF8zAzvEDqd2nbGp9iUH1bfwiZTnt9HcsRLqrgso
mode    : btc
version : 0080 (hex) 128 (BE) 32768 (LE)
payload : 617e729455b42dd6c12fcb0f16613d7251672e8cc12390a65d334dd36ca0335801
checksum: 3f508986 (hex) 1062242694 (BE) 2257145919 (LE)
```

```shell
$ echo 617e729455b42dd6c12fcb0f16613d7251672e8cc12390a65d334dd36ca03358|qx ec-to-wif
KzVE5hmNC6UpHF8zAzvEDqd2nbGp9iUH1bfwiZTnt9HcsRLqrgso
```

```shell
$ echo KzVE5hmNC6UpHF8zAzvEDqd2nbGp9iUH1bfwiZTnt9HcsRLqrgso|qx wif-to-ec
617e729455b42dd6c12fcb0f16613d7251672e8cc12390a65d334dd36ca03358
```

Comparison
![image](https://user-images.githubusercontent.com/22833166/89142895-44c9f000-d57b-11ea-86e7-b6c63d968dcd.png)
