### ISSUE TITLE
Lack of wallet_getTxListByAccount rpc interface

### ISSUE THREAD

**Issue by ArayofEntropy** [Qitmeer/qitmeer-wallet#52]
1. There are many addresses in an account
2. Every address may get receive or send transactions
3. I wanna monitor all my transactions
4. Only wallet_getTxListByAddr is not enough

**Comment by forchain** [comment]
@dindinw do we need to add this API. It is just an enhancement, we could work around it by two steps, list addresses by account and then retrieve tx from each address
