### ISSUE TITLE
wallet 启动后一直更新节点

### ISSUE THREAD

**Issue by huzhiyang888** [Qitmeer/qitmeer-wallet#56]
wallet 启动后一直更新节点   MainOrder: 0   MainHeight: 0

**Comment by forchain** [comment]
![71595853920_ pic_hd](https://user-images.githubusercontent.com/22833166/88607266-60cc1e00-d0b1-11ea-8f25-74be031b5762.jpg)

**Comment by forchain** [comment]
happens when updating blocks,

**Comment by forchain** [comment]
not reproducible
