### ISSUE TITLE
Qitmeer-Wallet FAQ

### ISSUE THREAD

**Issue by guosq02** [Qitmeer/qitmeer-wallet#63]
Qitmeer wallet failed to compile with make。Can you provide executable binaries?
![9D165C25-E571-4dad-97D4-13AADF53B34E](https://user-images.githubusercontent.com/29112794/95643357-57aff200-0ae1-11eb-8f95-13eb27d871a5.png)

**Comment by guosq02** [comment]
My Ubuntu version is Ubuntu 18.04.5

**Comment by guosq02** [comment]
My Ubuntu version is Ubuntu 18.04.5

**Comment by forchain** [comment]
@guosq02 dear friend, it seemed that you failed to load some dependency, probably due to network connectivity issue. Please follow the instruction in ReadMe.

![image](https://user-images.githubusercontent.com/22833166/95668689-f99b1180-0ba9-11eb-9984-a806b0b7cd7a.png)

**Comment by guosq02** [comment]
I used this agent to compile too slowly. It has not been finished since I started compiling in the morning

# HTTP proxy
export HTTP_PROXY=http://proxy.example.com:8080

# NPM proxy
npm config set proxy http://proxy.example.com:8080

**Comment by guosq02** [comment]
You can't open this website
![Uploading image.png…]()

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95729371-61875000-0caf-11eb-8614-fd208729a9e0.png)
The domain name couldn't be found

**Comment by forchain** [comment]
@guosq02  example.com is NOT A REAL website, you should replace it with a REAL proxy.
You also could try some public proxy, please see https://developer.aliyun.com/mirror/NPM

**Comment by forchain** [comment]
```sh
./qitmeer-wallet web
```

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95837638-64e40f80-0d73-11eb-90d4-8609ebd2a644.png)
![image](https://user-images.githubusercontent.com/29112794/95837703-7a593980-0d73-11eb-9252-e8d4ea4772ba.png)

Unable to request data

**Comment by forchain** [comment]
please share your config.toml

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95838865-dff9f580-0d74-11eb-8f60-ac92cc25cb9d.png)
Do you want me to create a wallet first? Use. / qitmeer wallet QC create

**Comment by guosq02** [comment]
![Uploading image.png…]()

**Comment by forchain** [comment]
do you have an account named "test_account" ? It seems that you just copied and pasted the sample commands from the API document. Please note, all the commands are just for demonstration , they worked only on my machine and won't be applied on yours.You should modify those commands accordingly.

From the last error message we know that you didn't have an account named "test_account", therefore you cannot create an address belonging to it. Please follow those step as I wrote in the ReadMe.

1. Create a wallet
2. create an account, if you don't want to, you may use the default account, whose name is "default"
3. create addresses and specify the owner account as you just created in step 2

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95841697-3f0d3980-0d78-11eb-8a93-09202c2e755f.png)
openWallet err:invalid passphrase for master public key

How do I fill in

**Comment by forchain** [comment]
this is the password that you specified during WALLET CREATION.

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95842780-8cd67180-0d79-11eb-9f89-c53f2b0a2465.png)

**Comment by forchain** [comment]
https://qitmeer.github.io/docs/en/wallet-json-rpc-api/instruction/

please follow the instruction of JSON RPC API.

Did you run the wallet web service? The JSON RPC replied on this service.
```sh
./qitmeer-wallet web
```

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95843985-f73be180-0d7a-11eb-87b5-c39557c7f11b.png)

**Comment by forchain** [comment]
please check your config.toml, make sure your rpcUser and rpcPass are consistent with those of your requests.


Please note this part in the API instruction
![image](https://user-images.githubusercontent.com/22833166/95844657-babcb580-0d7b-11eb-8345-03c247afafdf.png)

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95845952-674b6700-0d7d-11eb-964e-e3b48a752d35.png)
![image](https://user-images.githubusercontent.com/29112794/95846032-84803580-0d7d-11eb-8beb-10f787e658f0.png)
The information should be correct

**Comment by forchain** [comment]
please check the Qitmeerds section. **18130** is supposed to be the default P2P port, and the default RPC port would be **18131**

**Comment by guosq02** [comment]
It's the same as before.
Is there a problem with the IP of the qitmeerds part?

**Comment by guosq02** [comment]
![Uploading image.png…]()

**Comment by forchain** [comment]
> ![image](https://user-images.githubusercontent.com/29112794/95838865-dff9f580-0d74-11eb-8f60-ac92cc25cb9d.png)
> Do you want me to create a wallet first? Use. / qitmeer wallet QC create

Form your previous steps, we could infer that RPC calls worked on your machine before, at least there was no connection problem. You could relaunch your wallet API service to see if the service recovers again. Or you could enter the Web UI (locahost:8130/app) to see if RPC is working.  Since the browser sends RPC calls to wallet web service as well, you may try this to tell if it is the wallet service's problem or the CLI problem.

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95854783-ff4f4d80-0d89-11eb-9dae-1eb1afbbbf9e.png)
The node data is not synchronized to the height of 0. I need to set it config.toml Is there a configuration of the file?

**Comment by guosq02** [comment]
![Uploading image.png…]()

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95933726-d9fe2600-0e01-11eb-8013-edc867ac5275.png)
I configured the qitmeer node in the qitmeerds section, but I still couldn't get the correct height

**Comment by guosq02** [comment]
I can synchronize node data

I need to be in confing.toml What parameters are configured in the file.
Can I request services on Ubuntu only if I have a local postman?

**Comment by guosq02** [comment]
Sending transaction returns txid, but there is no way to query transaction information through txid. How do I query transaction information?

**Comment by guosq02** [comment]
![image](https://user-images.githubusercontent.com/29112794/95979897-ef4d7180-0e4e-11eb-8835-1ffae4c5cc01.png)
How do I enter my wallet code?
I haven't seen this wallet password

**Comment by guosq02** [comment]
How to distinguish between recharge and withdrawal in Vout of transaction information?

**Comment by forchain** [comment]
> Sending transaction returns txid, but there is no way to query transaction information through txid. How do I query transaction information?

Indeed, we missed it, I created an issue for this and am working on it. Thank you
https://github.com/Qitmeer/qitmeer-wallet/issues/64

**Comment by forchain** [comment]
> ![image](https://user-images.githubusercontent.com/29112794/95979897-ef4d7180-0e4e-11eb-8835-1ffae4c5cc01.png)
> How do I enter my wallet code?
> I haven't seen this wallet password

You need to unlock the wallet first
https://qitmeer.github.io/docs/en/wallet-json-rpc-api/api-list/wallet_unlock/

**Comment by forchain** [comment]
> How to distinguish between recharge and withdrawal in Vout of transaction information?

If the sum of your UTXOs in your inputs is greater than that in your outputs, it is a withdraw, otherwise a deposit.
