### ISSUE TITLE
[0.10-dev]cannot open account management in web 

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-wallet#95]
1. open wallet-ui
```
 ./build/bin/qitmeer-wallet web
```

2. select  account management

3. error
```
code:-32602

info:non-array args
```
![image](https://user-images.githubusercontent.com/22833166/121127469-67dcc480-c85c-11eb-85d6-82e6eb87eadf.png)

**Comment by bCoder778** [comment]
Has been fixed in the latest PR
